# This file configures the Dependabot. See
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignoring the Firebase dependencies because they require also updating
      # macos/Podfile and ios/Podfile (to apply the workaround for
      # https://github.com/FirebaseExtended/flutterfire/issues/2751)
      - dependency-name: cloud_firestore
      - dependency-name: firebase_core
      - dependency-name: firebase_storage
      - dependency-name: firebase_auth
      - dependency-name: cloud_functions
