# This file configures the Dependabot. See
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
