include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    # Generated files with Mockito
    - "**/**.mocks.dart"
  errors:
    # We need to ignore these errors, because of @JsonKey in freezed files:
    # https://github.com/rrousselGit/freezed/issues/488.
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
