name: ankigpt
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-126.0.dev <4.0.0"

dependencies:
  cloud_functions: ^4.3.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logger: ^1.3.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  icons_launcher: ^2.1.0

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    web:
      enable: true
      image_path: "assets/logo.png"
      favicon_path: "assets/favicon.png"
    macos:
      enable: true
      image_path: "assets/macos.png"