name: ankigpt
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  chewie: ^1.5.0
  cloud_functions: ^4.3.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logger: ^1.3.0
  package_info_plus: ^3.1.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.11
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
