name: ankigpt
description: Generate flashcards from the lecture slides with one click and
  easily export them to Anki.
publish_to: "none"
version: 1.0.0+1
repository: https://github.com/nilsreichardt/ankigpt

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  chewie: ^1.5.0
  clock: ^1.1.1
  cloud_firestore: ^4.9.3
  cloud_functions: ^4.4.2
  collection: ^1.17.2
  confetti: ^0.7.0
  cross_file: ^0.3.3+4
  cupertino_icons: ^1.0.5
  easy_debounce: ^2.0.3
  file_picker: ^6.1.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.0
  plausible_analytics: ^0.3.0
  queue:
    git:
      url: https://github.com/nilsreichardt/dart_queue
      ref: a535dcc522d7104c2719cc6f9c4d198c6501c443
  retry: ^3.1.2
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  super_drag_and_drop: ^0.8.5
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  video_player: ^2.8.2
  wiredash: ^2.1.0
  wolt_responsive_layout_grid: ^0.0.3

dev_dependencies:
  # Using a fork because adaptive_test couldn't load the fonts.
  adaptive_test:
    git:
      url: https://github.com/nilsreichardt/adaptive_test
      ref: 7768b756e1298e888d902c98742b2de02089a8df
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  path: ^1.8.3
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
