name: ankigpt
description: Generate flashcards from the lecture slides with one click and easily export them to Anki.
publish_to: "none"
version: 1.0.0+1
repository: https://github.com/nilsreichardt/ankigpt

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  chewie: ^1.5.0
  cloud_firestore: ^4.8.0
  cloud_functions: ^4.3.1
  collection: ^1.17.2
  confetti: ^0.7.0
  cross_file: ^0.3.3+4
  cupertino_icons: ^1.0.5
  easy_debounce: ^2.0.3
  file_picker: ^5.2.10
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.3.0
  package_info_plus: ^3.1.2
  queue:
    git:
      url: https://github.com/nilsreichardt/dart_queue
      ref: a535dcc522d7104c2719cc6f9c4d198c6501c443
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  golden_toolkit: ^0.15.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
