name: main

concurrency:
  group: main

on:
  push:
    branches:
      - main
    paths:
      - ".fvm/**"
      - "lib/**"
      - "assets/**"
      - "fonts/**"
      - "web/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/main.yml"
      - "firebase.json"
      - ".firebaserc"

# Set permissions to none.
#
# Using the broad default permissions is considered a bad security practice
# and would cause alerts from our scanning tools.
permissions: {}

jobs:
  build_and_deploy:
    name: build-and-deploy-${{ matrix.environment.name }}
    runs-on: ubuntu-22.04
    permissions:
      checks: write # for FirebaseExtended/action-hosting-deploy
      contents: "read" # for google-github-actions/auth
      id-token: "write" # for google-github-actions/auth
    strategy:
      matrix:
        environment:
          - name: prod
            projectNumber: 41416187582
            projectId: ankigpt-prod
            flavor: prod
          - name: dev
            projectNumber: 531541464051
            projectId: ankigpt-dev
            flavor: dev
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set Flutter version from FVM config file to environment variables
        uses: kuhnroyal/flutter-fvm-config-action@e91317131a2da710b9cd9b7a24f2c0ade9eeb61d

      - uses: subosito/flutter-action@main
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build
        run: |
          flutter build web \
            --web-renderer canvaskit \
            --dart-define=RELEASE_DATE="$(date +"%B %e %Y")" \
            --dart-define=FLAVOR="${{ matrix.environment.flavor }}"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/${{ matrix.environment.projectNumber }}/locations/global/workloadIdentityPools/github/providers/github-provider"
          service_account: "github-action-644087301@${{ matrix.environment.projectId }}.iam.gserviceaccount.com"

      # From https://github.com/FirebaseExtended/action-hosting-deploy/issues/174#issuecomment-1312272238
      - name: Set SERVICE_ACCOUNT_KEY to environment variables
        run: |
          echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

      - uses: FirebaseExtended/action-hosting-deploy@120e124148ab7016bec2374e5050f15051255ba2
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ env.SERVICE_ACCOUNT_KEY }}"
          channelId: live
          target: ankigpt-app
          projectId: "${{ matrix.environment.projectId }}"
